name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - feature/*

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Authenticate Salesforce Org
    - name: Authenticate Salesforce Dev Org
      env:
        SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
      run: sfdx auth:sfdxurl:store --setalias DevOrg --noninteractive

    # Step 3: Install Salesforce CLI
    - name: Install Salesforce CLI
      uses: amtrack/sfdx-actions@v2
      with:
        version: latest

    # Step 4: Run Code Validation
    - name: Validate Code (Apex Tests, Lint, etc.)
      run: |
        sfdx force:source:push -u DevOrg
        sfdx force:apex:test:run --resultformat human --outputdir test-results --wait 10
        sfdx force:source:delete -u DevOrg -p force-app --noprompt

    # Step 5: Approve and Merge Code to Main
    - name: Merge Code to Main Branch
      if: success() && github.ref == 'refs/heads/feature/*'
      uses: actions/github-script@v6
      with:
        script: |
          const { execSync } = require('child_process');
          execSync('git checkout main');
          execSync('git merge ${{ github.ref }}');
          execSync('git push origin main');

    # Step 6: Deploy to Dev Org
    - name: Deploy to Development Org
      run: |
        sfdx force:source:deploy -u DevOrg -p force-app
