name: Salesforce Metadata Sync

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  sync-metadata:
    runs-on: windows-latest  # Using Windows for PowerShell compatibility

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      # Step 3: Verify Salesforce CLI Installation
      - name: Verify sf CLI Installation
        run: sf --version

      # Step 4: Authenticate Source Org (ares1Org)
      - name: Authenticate Source Org
        run: |
          sf login web --setalias ares1Org --instance-url https://login.salesforce.com
        shell: pwsh  # Use PowerShell for execution

      # Step 5: Authenticate Target Org (ares2Org)
      - name: Authenticate Target Org
        run: |
          sf login web --setalias ares2Org --instance-url https://login.salesforce.com
        shell: pwsh

      # Step 6: Run the PowerShell Script
      - name: Execute Sync Script
        shell: pwsh
        run: ./scripts/SyncMetadata.ps1
