name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - Feature_210325  # Trigger on any feature branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Adjust to your Node.js version requirement

    - name: Install Salesforce CLI
      run: |
        npm install -g sfdx-cli

    - name: Authenticate with Salesforce
      run: |
        echo ${DEV_AUTH_URL} > auth_url.txt
        sfdx auth:sfdxurl:store -f auth_url.txt
        rm auth_url.txt
      env:
        DEV_AUTH_URL: ${{ secrets.SFDX_AUTH_URL1 }}

    - name: Deploy to Dev Org
      run: |
        sfdx force:source:deploy -p force-app --targetusername DevOrg

    - name: Merge to Main Branch
      if: success()
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<your-email>"
        git checkout main
        git merge ${{ github.ref_name }}
        git push
